branches:
  only:
    - travis-ci
language: ruby
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_VERSION=1.11.2-0~trusty
    - DOCKER_COMPOSE_VERSION=1.7.1
  matrix:
    - TAG=latest RAILS_VERSION=\~\>5.0.0
    - TAG=latest RAILS_VERSION=\~\>4.2.0
    - TAG=latest RAILS_VERSION=\~\>4.1.0
    - TAG=latest RAILS_VERSION=\~\>4.0.0
    - TAG=latest RAILS_VERSION=\~\>3.2.0
    - TAG=slim RAILS_VERSION=\~\>5.0.0
    - TAG=slim RAILS_VERSION=\~\>4.2.0
    - TAG=slim RAILS_VERSION=\~\>4.1.0
    - TAG=slim RAILS_VERSION=\~\>4.0.0
    - TAG=slim RAILS_VERSION=\~\>3.2.0
    - TAG=alpine RAILS_VERSION=\~\>5.0.0
    - TAG=alpine RAILS_VERSION=\~\>4.2.0
    - TAG=alpine RAILS_VERSION=\~\>4.1.0
    - TAG=alpine RAILS_VERSION=\~\>4.0.0
    - TAG=alpine RAILS_VERSION=\~\>3.2.0
    - TAG=mini RAILS_VERSION=5
    - TAG=mini RAILS_VERSION=4

matrix:
  allow_failures:
    - env: TAG=mini RAILS_VERSION=5
    - env: TAG=mini RAILS_VERSION=4

# http://graysonkoonce.com/managing-docker-and-docker-compose-versions-on-travis-ci/
before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

  # reinstall docker-compose at specific version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker version
  - docker-compose version

script:
  - docker build -f Dockerfile.${TAG} -t nooulaif/rails:${TAG} .
  - cd test
  - if [[ "$RAILS_VERSION" == "3" ]]; then cd rails3; fi
  - sed -i "s/latest/${TAG}/g" docker-compose.yml
  - export TRAVIS_USER_ID=$(id -u)
  - docker-compose -p example up
  - docker logs example_app_1 | grep 'Bundle complete!'
  - docker logs example_app_1 | grep "Using rails $RAILS_VERSION"
  - ls db | grep '.sqlite3'
  - if [[ "$TAG" != "mini" ]]; then docker-compose run -e NO_INSTALL=true app /bin/bash -c 'gem install pg'; fi
  - if [[ "$TAG" != "mini" ]]; then docker-compose run -e NO_INSTALL=true app /bin/bash -c 'gem install mysql'; fi
  - docker-compose -p example up -d && sleep 3
  - curl -X GET http://localhost:3000/
